name: 'Automatic Build on Push'
on:
  push:
    branches:
      - master

jobs:
  continuous-delivery:
    runs-on: ubuntu-20.04
    
    steps:
        - uses: actions/checkout@v2
        
        - name: Setting up Python Environment
          uses: actions/setup-python@v2
          with:
              python-version: '3.8' 
              architecture: 'x64'
                
        - name: Install Python Dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
        - name: Submodule Init for Data
          run: |
            git submodule update --init --remote --depth 1
            
        - name: Build Pages Json Data
          run: |
            python DataPreprocessing.py
            
        - name: Get Current Time
          id: currenttime
          run: echo "::set-output name=now::$(date +'%Y/%m/%d-%H:%M:%S-UTC' --utc)"
        
        - name: Add CNAME
          run: echo "www.wearamask.ml" > pages/CNAME
            
        - name: Deploy to Pages
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: pages
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SQUASH_HISTORY: true
            SKIP_EMPTY_COMMIT: true
            MESSAGE: ${{ steps.currenttime.output.now }}
        
    
